var baseServiceURL = "http://localhost/MatematickiMajstor/server/php/";
var URLSessionTest = baseServiceURL + "test_session.php";
var URLRegisterPost= baseServiceURL + "register.php";
var URLLoginPost = baseServiceURL + "login.php";
var URLLogout = baseServiceURL + "logout.php";
var URLGetPlayerStats = baseServiceURL + "stats_player.php";
var URLGetRatioStats = baseServiceURL + "stats_most_successful.php";
var URLGetMostPlayedStats = baseServiceURL + "stats_most_played.php";
var URLGetFastestPlayerStats = baseServiceURL + "stats_time_fastest.php";
var socketURL = "127.0.0.1:8080"; // Use 95.85.6.210:8080 for remote server if you don't run node.js on localhost